### ISSUE TITLE
运行报错RuntimeError: Install Flask with the 'async' extra in order to use async views.

### ISSUE THREAD

**Issue by zhuceney** [QXAzusa/cqhttp-msg-push#3]
使用的是最新的go-cqhttp和push
具体报错信息如下：
127.0.0.1 - - [25/Aug/2022 21:36:00] "POST / HTTP/1.1" 500 -
[2022-08-25 21:36:05,074] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\zcy\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\zcy\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\zcy\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zcy\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\zcy\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1606, in ensure_sync
    return self.async_to_sync(func)
  File "C:\Users\zcy\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1627, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.

**Comment by QXAzusa** [comment]
依赖aioflask安装了吗？
重新跑一次'pip install aioflask'看看呢

https://stackoverflow.com/questions/70321014/runtimeerror-install-flask-with-the-async-extra-in-order-to-use-async-views

**Comment by zhuceney** [comment]
https://stackoverflow.com/questions/70321014/runtimeerror-install-flask-with-the-async-extra-in-order-to-use-async-views
我跟着[se7enXF]再安装了 asgiref 这个依赖就不报错了🤣
